name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .
    - name: Run tests
      run: python -m unittest tests/test_demo.py
